### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by einarf**

### CODE REVIEW

**Comment by einarf** [comment]
Coverage is about ~75%. A good start.

Feel free to merge.

**Comment by einarf** [comment]
80%. Think I'm done for now. Missing tests for name prefix etc, but I guess it's not realistic to get 100%.. at least not in first PR.

**Comment by einarf** [comment]
~84% coverage now. That's all I have the energy for now.

**Comment by einarf** [comment]
Found the courage to add a few more tests reaching 91% coverage.

**Comment by blacktorn** [comment]
Wow, this is amazing work! 💯

**Pull request merged**
