### PR TITLE
Add region name parameter

### PR DESCRIPTION
**Pull request by einarf**
Adds region name parameter.

Not tested, so don't merge yet! I think this is the only thing needed though.

### CODE REVIEW

**Comment by einarf** [comment]
Closed and reopened PR to trick travis into rebuilding. Something went wrong with init of a 2.7 env.

**Comment by einarf** [comment]
I'll leave it here for a couple of hours. Travis is angry today.

**Comment by blacktorn** [comment]
Might be caused by this commit in django master:
https://github.com/django/django/commit/3cc5f01d9bd52930cec3c08d6ec7e19d0c2a6489

**Comment by einarf** [comment]
@blacktorn You are right. `functools.lru_cache` is python 3 only.

It seem that master is now Django 2.0 that dropped support for python 2.

**Comment by einarf** [comment]
@blacktorn Yep. Just coffee overdose today :D

**Comment by einarf** [comment]
Tested. Works!

**Pull request merged**
